services:
  web:
    build: .
    platform: linux/arm64/v8
    volumes:
      - ".:/rails"
    ports:
      - 80:3000
    networks:
      - sail
  mysql:
    image: "mysql:8"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "sail-mysql:/var/lib/mysql"
    networks:
      - sail
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    platform: linux/amd64/v8
    ports:
      - "5005:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
